[travis] Fix Nix issues
Two regressions appeared in Nix:

* Nixpkgs dropped support for the Bazaar package.
* Nixpkgs started requiring a version of Nix newer than 2.0.4. Wihout
  upgrading, installing packages such as exercism failed with the
  following error:

    error: unknown hash algorithm '', at /nix/store/xack9d46l4dalj3h7iasmmiajx1rif1k-nixpkgs-20.09pre228165.00df2371122/nixpkgs/pkgs/build-support/fetchurl/default.nix:119:3

Work around these issues by upgrading Nix on Travis CI and by installing
Bazaar using the system's package manager.