[zsh] Fix 'nix-shell' breaking on Linux
NIX_PATH is not exported on my Linux machine (strapurp) for some reason.
I guess the profile.d script doesn't do it. This causes nix-shell to
fail:

    $ nix-shell -p vim
    error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

           at «string»:1:25:

                1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (vim) ]; } ""
                 |                         ^
    (use '--show-trace' to show detailed location information)

Export NIX_PATH explicitly, fixing nix-shell (and possibly other
commands).