[nix] Fix install-packages on macOS
Running the install-packages script on macOS fails with the following
error:

    error: file nixpkgs.iterm2 not found (searched /Users/strager/.nix-profile/nixpkgs.iterm2)

The error is caused by a typo; nixpkgs.iterm2 is added to the wrong
array. Add it to the correct array, fixing the error.

For Travis CI and for Linux, this commit should not change behavior.